apiVersion: skillimage.io/v1alpha2
kind: SkillCard
metadata:
  version: 1.0.0
  title: Hello World
  vendor: OCTO Team
  tags:
    - example
    - getting-started
  authors:
    - name: OCTO Team
      email: octo@redhat.com
